### ISSUE TITLE
M1

### ISSUE THREAD

**Issue by footballs-w-edits** [Miracle0565/ComplementaryShaders#3]
Can you please help in making the shaders compatible with M1? It would have been my favorite if it wasn't for the compatibility.

**Comment by Miracle0565** [comment]
Sorry, we can't. We are **NOT** the developer of the shaders, but do the translation into Chinese. [See the Intro of the repo](https://github.com/Miracle0565/ComplementaryShaders#introduction).

However, the shaders were released on [curseforge](https://www.curseforge.com/minecraft/customization/complementary-shaders). You may write your comments below, or post your help and suggestions on the [Discord](https://discord.com/invite/A6faFYt). These may be the proper places where the developers collect feedback, I think.

May it helps you :-)

**Comment by Miracle0565** [comment]
Good news: Complementary v4 is now compatible with Apple M1 devices from Complementary v4.5.

See also: [Changelog](https://www.curseforge.com/minecraft/customization/complementary-shaders/files/3826772).
