### ISSUE TITLE
关于2个强迫症的小问题

### ISSUE THREAD

**Issue by jcjyids** [Miracle0565/ComplementaryShaders#5]
在鼠标放到一些选项上时，会提示具体信息，这些信息在原作者的排版下很整齐，但翻译后没有与原格式匹配，如果你们愿意可以将格式统一。

现汉化文件效果：

![image](https://user-images.githubusercontent.com/74102874/219730053-68af4f48-ed13-4410-9f91-cc037dac011f.png)

修改后效果：（顺手删了句号，并把极高统一）

![image](https://user-images.githubusercontent.com/74102874/219728591-a6c25678-e9c4-49f6-bb61-72fde4a3896a.png)

profile.comment=§4极低:§r 禁用阴影和水面反射. §6低:§r 降低阴影的分辨率和可视距离. §e中:§r 禁用镜面反射. §a原版 / 类 RTX:§r 带有原版风格的高配置. §b高（默认）:§r 默认的光影体验. §9超高:§r 启用一些额外的特效. §d极限:§r 终极光影体验

![image](https://user-images.githubusercontent.com/74102874/219732698-2a659306-ed76-496d-aa5f-6b6bd94936f0.png)

第二个问题不是问题，选项里是超高，提示里是极高

![image](https://user-images.githubusercontent.com/74102874/219731272-0a619223-2a15-4ddb-8eee-6f645855e2fc.png)

**Comment by Miracle0565** [comment]
您的问题可以复现。

以下测试使用 Iris 1.2.0-pre 和光影 4.7.1 版本，汉化文档使用 [4.7b](https://github.com/Miracle0565/ComplementaryShaders/blob/8dee088c3e4ce41ff6a84a8ff6fa977643c5a5f0/zh_CN.lang) 。

## 第一个问题：格式排版

据我目前的测试来看，汉化后丢失了换行是因为汉化文档将句末的西文句点和空格 `. ` 改为了中文句号 `。` 。
正如您的例子里，将 [原先文本](https://github.com/Miracle0565/ComplementaryShaders/blob/370cf98156580ce65497c3e38705e2599081524f/zh_CN.lang#L12) 

```
profile.comment=§4极低：§r 禁用阴影和水面反射。 §6低：§r 降低阴影的分辨率和可视距离。 §e中：§r 禁用镜面反射。 §a原版 / 类 RTX：§r 带有原版风格的高配置。 §b高（默认）：§r 默认的光影体验。 §9超高：§r 启用一些额外的特效。 §d极限：§r 终极光影体验。
```

中的中文标点修改为西文标点：

```
profile.comment=§4极低:§r 禁用阴影和水面反射. §6低:§r 降低阴影的分辨率和可视距离. §e中:§r 禁用镜面反射. §a原版 / 类 RTX:§r 带有原版风格的高配置. §b高（默认）:§r 默认的光影体验. §9超高:§r 启用一些额外的特效. §d极限:§r 终极光影体验
```

即可保留原本排版，初步猜想是因为 `. ` 起到了换行的作用——但我目前还不知道是不是 Iris 的缘故。

另外，在本项目所参考的 [Minecraft Mod 简体中文翻译规范与指南](https://github.com/Krasjet/Mod-Translation-Styleguide) 中 [第三节：标点符号](https://github.com/Krasjet/Mod-Translation-Styleguide#03标点符号) 提及：

> 请与原版 Minecraft 保持统一，使用中文的标点符号。
> 对于英文标点符号前或后的空格，请在修改标点符号为中文时删除。

虽然以英文显示时的句末并无句点，但我个人还是倾向于加上标点。因此，在仍然遵守规范的情况下，做如下修改可以兼顾二者：

```
profile.comment=§4极低：§r 禁用阴影和水面反射。. §6低：§r 降低阴影的分辨率和可视距离。. §e中：§r 禁用镜面反射。. §a原版 / 类 RTX：§r 带有原版风格的高配置。. §b高（默认）：§r 默认的光影体验。. §9超高：§r 启用一些额外的特效。. §d极限：§r 终极光影体验。
```

虽然这样的汉化文件看上去似乎有点奇怪，但是实现的效果还不错：

![srcshot](https://user-images.githubusercontent.com/53522776/219761660-cf18cfc7-4c43-46af-8f42-a7c885c19d82.png)

如果您认为这样可以，我会在近期将修改版本发布到本仓库的 [dev 分支](https://github.com/Miracle0565/ComplementaryShaders/tree/dev) ；并且，如果最后没有其他问题，我会合并到 main 里。

最后 值得一提的是，部分中文标点的渲染不正确是因为 Minecraft 自身有问题，例如 [MC-241824](https://bugs.mojang.com/browse/MC-241824) 等。所以即便有参考规范，是选用中文标点还是西文标点甚至干脆不要标点我也很纠结。希望 @Wudji 能给点建议 = =

## 第二个问题：“超高”和“极高”不统一

发生原因：是汉化文件在 [Line10](https://github.com/Miracle0565/ComplementaryShaders/blob/370cf98156580ce65497c3e38705e2599081524f/zh_CN.lang#L10)：

```
profile.ULTRA=§9超高
```

和在 [Line12](https://github.com/Miracle0565/ComplementaryShaders/blob/370cf98156580ce65497c3e38705e2599081524f/zh_CN.lang#L12) ：

```
profile.comment=§4极低：§r 禁用阴影和水面反射。 §6低：§r 降低阴影的分辨率和可视距离。 §e中：§r 禁用镜面反射。 §a原版 / 类 RTX：§r 带有原版风格的高配置。 §b高（默认）：§r 默认的光影体验。 §9极高：§r 启用一些额外的特效。 §d极限：§r 终极光影体验。
```

前后不统一引起。感谢提醒，我将会把“极高”统一为“超高”。

**Comment by jcjyids** [comment]
是的，测试表明句末的`. `是换行标志，并且其本身并不会显示，在我测试OptiFine和iris中，`. `起到的作用相同。

关于标点：在中文语句中应该使用中文标点，但在合适的地方、不影响语句含义时我觉得可以省去标点。

-[这个界面](https://user-images.githubusercontent.com/53522776/219761660-cf18cfc7-4c43-46af-8f42-a7c885c19d82.png)中的句号我认为是可以删去的，但保留并不会带来不合适的感觉，保留自然也可以接受

-[这个界面](https://user-images.githubusercontent.com/74102874/219730053-68af4f48-ed13-4410-9f91-cc037dac011f.png)中，由于不同句子显示在同一行，需要句号来做分割。

-但如果原文的`极限：终极光影体验`的末尾是个叹号`!`，那么我认为保留叹号的同时，其他行不要添加句号，提高特殊性，给使用者的感觉就像是这会超过你的预期，或选择这个选项需要心理准备。
